version: "3.3"
services:
    mongodb:
        image: mongo:3.6-jessie
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

    master:
        image: plynxteam/backend:latest
        container_name: "master"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
        command: plynx worker -vvv -e basic-dag-workflow

    workers:
        image: plynxteam/backend:latest
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
        command: plynx worker -vvv -e basic-bash-jinja2-operation -e basic-python-node-operation -e basic-dag-operation

    api:
        image: plynxteam/backend:latest
        container_name: "api"
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
        command: plynx api -vvv

    test:
        image: plynxteam/backend:latest
        container_name: "test"
        depends_on:
            - api
        links:
            - api
            - mongodb
        environment:
            - PLYNX_ENDPOINT=http://api:5000/plynx/api/v0
        command: ./scripts/run_tests.sh

    frontend:
        image: plynxteam/ui:latest
        container_name: "frontend"
        ports:
            - "3001:80"
        depends_on:
            - api
        links:
            - api
