version: "3.3"
services:
    mongodb:
        image: mongo:3.6-jessie
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./test/integration/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    master:
        image: khaxis/plynx:master
        container_name: "master"
        ports:
            - 17011:17011
        depends_on:
            - mongodb
        links:
            - mongodb
    workers:
        image: khaxis/plynx:worker
        volumes:
            - disk-storage:/data
        depends_on:
            - master
        links:
            - master
            - mongodb
    backend:
        image: khaxis/plynx:backend
        container_name: "backend"
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - disk-storage:/data
    test:
        image: khaxis/plynx:test
        container_name: "test"
        depends_on:
            - backend
        links:
            - backend
            - mongodb

    frontend:
        image: khaxis/plynx:ui
        container_name: "frontend"
        ports:
            - "3001:80"
        depends_on:
            - backend
        links:
            - backend

volumes:
    disk-storage:
