version: 2
jobs:
  build:
    machine: true
    working_directory: ~/plynx
    steps:

      - checkout

      - run:
          name: install requirements
          command:
            set -x
            pip install --upgrade pip &&
            pip install google-compute-engine flake8
            flake8 --version

      - run:
          name: flake8
          command: flake8

      - run:
          # note we need to install google-compute-engine due to circleci issue
          name: python package instalation
          command:
            python setup.py install

      - run:
          name: Run integration tests
          command: make run_tests
