version: 2
jobs:
  python_build:
    working_directory: ~/plynx
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install requirements
          command:
            set -x
            pip install --upgrade pip &&
            pip install google-compute-engine flake8 pytest twine
            flake8 --version
      - run:
          # run earlier to save time
          name: flake8
          command: flake8
      - run:
          # note we need to install google-compute-engine due to circleci issue
          name: python package instalation
          command:
            make package

  python_test:
    working_directory: ~/plynx
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Run tests
          command: make run_tests

  python_deploy:
    working_directory: ~/plynx
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_TOKEN" >> ~/.pypirc
            echo -e "password = # No needed" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*
  build_docker:
    machine: true
    steps:
      - checkout
      - run:
          make build
workflows:
  version: 2
  build_and_test:
    jobs:
      - python_build
      - python_test
        requires:
          - python_build
