version: 2
jobs:
  build:
    machine: true
    working_directory: ~/plynx
    steps:

      - checkout

      - run:
          name: install requirements
          command:
            pip install --upgrade pip &&
            pip install google-compute-engine flake8

      - run:
          name: flake8
          command: flake8
