version: 2
jobs:
  build_package:
    working_directory: ~/plynx
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            set -x
            pip install --upgrade pip
            pip install google-compute-engine flake8 pytest twine
      - run:
          # run earlier to save time
          name: flake8
          command: flake8
      - run:
          # note we need to install google-compute-engine due to circleci issue
          name: python package instalation
          command:
            # make build_package
            sudo python setup.py install

  build_docker:
    machine: true
    steps:
      - checkout
      - run:
          name: copy config file
          command: cp template_config.yaml config.yaml
      - run:
          name: build docker images
          command: make build
      - run:
          name: Run tests
          command: make run_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_package
      - build_docker
