apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
      - image: khaxis/plynx:base
        name: master
        command:
          - plynx
          - master
          - "-vvvv"
          - "--db-host"
          - mongo
          - "--internal-master-host"
          - 0.0.0.0
        ports:
        - containerPort: 17011
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
