version: "3.3"
services:
  web:
    image: khaxis/plynx:worker
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    volumes:
      - type: bind
        source: ~/.boto
        target: /root/.boto
    extra_hosts:
      - "docker:192.168.1.8"
networks:
  webnet:
